In [2]:
import numpy as np

In [3]:
arr = np.array([[1,2,3],[4,5,6]])

In [5]:
type(arr)

numpy.ndarray

In [6]:
print(type(arr))

<class 'numpy.ndarray'>


In [8]:
arr.ndim

2

In [9]:
print(arr.ndim)

2


In [11]:
arr.shape

(2, 3)

In [12]:
arr1 = np.array([1,2,3])
arr1.shape

(3,)

In [15]:
c = np.zeros((3,4))

In [16]:
c

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [17]:
d = np.ones((3,4))

In [18]:
d

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [19]:
i = np.eye(3)

In [20]:
i

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [22]:
np.arange?

Docstring:
arange([start,] stop[, step,], dtype=None, *, like=None)

Return evenly spaced values within a given interval.

``arange`` can be called with a varying number of positional arguments:

* ``arange(stop)``: Values are generated within the half-open interval
  ``[0, stop)`` (in other words, the interval including `start` but
  excluding `stop`).
* ``arange(start, stop)``: Values are generated within the half-open
  interval ``[start, stop)``.
* ``arange(start, stop, step)`` Values are generated within the half-open
  interval ``[start, stop)``, with spacing between values given by
  ``step``.

For integer arguments the function is roughly equivalent to the Python
built-in :py:class:`range`, but returns an ndarray rather than a ``range``
instance.

When using a non-integer step, such as 0.1, it is often better to use
`numpy.linspace`.

See the Warning sections below for more information.

Parameters
----------
start : integer or real, optional
    Start of interval.  The interva

In [27]:
# create a sequence of integers from 0 to 30 with steps of 5
f = np.arange(0, 30, 5)
print("A sequnetial array with steps of 5\n", f)


#create a sequence of 10 values in range 0 to 5
g = np.linspace(0, 5, 10)
print("\n A sequential array with 10 values between 0 and 5\n", g)

A sequnetial array with steps of 5
 [ 0  5 10 15 20 25]

 A sequential array with 10 values between 0 and 5
 [0.         0.55555556 1.11111111 1.66666667 2.22222222 2.77777778
 3.33333333 3.88888889 4.44444444 5.        ]


In [28]:
arr = np.array([[1,2,3,4],
                [5,2,4,2],
                [3,5,7,9],])

newarr = arr.reshape(2,2,3)

In [29]:
newarr

array([[[1, 2, 3],
        [4, 5, 2]],

       [[4, 2, 3],
        [5, 7, 9]]])

In [30]:
arr[1:,:3]

array([[5, 2, 4],
       [3, 5, 7]])